version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: docutils
    versions:
    - "0.16"
    - "0.17"
  - dependency-name: pygments
    versions:
    - 2.7.4
    - 2.8.0
  - dependency-name: pytz
    versions:
    - "2020.5"
  - dependency-name: packaging
    versions:
    - "20.8"
  - dependency-name: cffi
    versions:
    - 1.14.4
